[build]
builder = "DOCKERFILE"
dockerfilePath = "./hasura-storage/Dockerfile"

[deploy]
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
healthcheckPath = "/healthz"
healthcheckTimeout = 100