[build]
builder = "DOCKERFILE"
dockerfilePath = "./hasura-auth/Dockerfile"

[deploy]
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
healthcheckPath = "/healthz"
healthcheckTimeout = 100